### ISSUE TITLE
프로젝트 구조 변경 제안

### ISSUE THREAD

**Issue by who-hoo** [Quokka-Squad/Seriously-Good-Software#8]
책 특성상 연습 문제로 미니 프로젝트를 해보거나, 예제 소스를 따라해보는 경우가 많은데요
지금의 디렉토리 구조로는 매 챕터마다 각자 프로젝트를 생성해야해서 불편함이 조금 있는데 디렉토리 구조를 이렇게 바꿔보는건 어떨까요?
- code
  - 각자의 프로젝트 루트 디렉토리(동기, 루이, ... 후)
    - 패키지로 챕터 구분
- docs
  - 동기
  - 루이
  - ...
  - 후
    - ch1.요약및연습문제풀이.md 
---
요약이든 연습문제풀이에 관련된 텍스트든 문서는 `docs` 디렉토리에 다 모으고,
main에 반영 후에 README.md에 주차별로 링크 걸어두면 보기도 편하고 좋을 것 같습니당

**Comment by ku-kim** [comment]
오 그런 구조가 훨씬더 좋아보여요!
이번주는 그대로 진행하고, 다음주부터 변경해볼까요?
